## Rasheed Hameed
## Assignment 2 
## Problem 1 - Newsgroup data


__For this problem you will use a subset of the 20 Newsgroup data set. The full data set contains 20,000 newsgroup documents, partitioned (nearly) evenly across 20 different newsgroups and has been often used for experiments in text applications of machine learning techniques, such as text classification and text clustering (see the description of the full dataset). The assignment data set contains a subset of 1000 documents and a vocabulary of  terms. Each document belongs to one of two classes Hockey (class label 1) and Microsoft Windows (class label 0). The data has already been split (80%, 20%) into training and test data. The class labels for the training and test data are also provided in separate files. The training and test data contain a row for each term in the vocabulary and a column for each document. The values in the table represent raw term frequencies. The data has already been preprocessed to extract terms, remove stop words and perform stemming (so, the vocabulary contains stems not full terms). Please be sure to read the readme.txt file in the distribution.__

__Your tasks in this problem are the following [Note: for this problem you should not use scikit-learn for classification, but create your own KNN classifer. You may use Pandas, NumPy, standard Python libraries, and Matplotlib.]__



In [1]:
import numpy as np
import pandas as pd


In [398]:
#Read in all the datasets
modifiedterms = pd.read_csv("newsgroups/modifiedterms.txt",header=None)
testClasses = pd.read_csv("newsgroups/testClasses.txt", sep='\t',header=None, index_col=0)
testMatrixModified = pd.read_csv("newsgroups/testMatrixModified.txt", sep = '\t', header=None)
trainClasses = pd.read_csv("newsgroups/trainClasses.txt", sep = '\t', header=None, index_col=0)
trainMatrixModified = pd.read_csv("newsgroups/trainMatrixModified.txt", sep = '\t', header=None)

In [3]:
#using numpy to make data arrays for future use
trainMatrix = np.array(trainMatrixModified)
#train matrix transponsed
trainMatrixt = np.transpose(trainMatrix)

testMatrix = np.array(testMatrixModified)
#test matrix transposed
testMatrixt = np.transpose(testMatrix)

In [4]:
#modifiedterms.txt: This file contains the set of 5500 terms in the vocabulary. 
#Each line contains a term and corresponds to the corresponding rows in term-document frequency matrices. 
modifiedterms.head()

0
0    david
1      rex
2     wood
3  subject
4     call

In [5]:
#testClasses.txt: This file contains the labels associated with each test document. 
#Each line is in the format of documentIndex \t classId where the documentIndex is in the 
#range of [0,200) and refers to the index of the document in the term-document frequency matrix for test documents  
testClasses.head()

1
0   
0  1
1  0
2  0
3  1
4  1

In [43]:
#testMatrixModified.txt: the term-document frequency for the test documents. The matrix contains 5500 rows and 200 columns.
testMatrixModified.head(), testMatrixt.shape

(   0    1    2    3    4    5    6    7    8    9    ...  190  191  192  193  \
 0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
 1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
 2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
 3  1.0  1.0  1.0  1.0  1.0  1.0  2.0  1.0  1.0  1.0  ...  1.0  2.0  1.0  1.0   
 4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0  ...  0.0  0.0  0.0  0.0   
 
    194  195  196  197  198  199  
 0  0.0  0.0  0.0  0.0  0.0  0.0  
 1  0.0  0.0  0.0  0.0  0.0  0.0  
 2  0.0  0.0  0.0  0.0  0.0  0.0  
 3  1.0  1.0  1.0  1.0  1.0  1.0  
 4  0.0  0.0  0.0  0.0  0.0  0.0  
 
 [5 rows x 200 columns], (200, 5500))

In [7]:
#trainClasses.txt: This file contains the labels associated with each training document. 
#Each line is in the format of documentIndex \t classId where the documentIndex is in the range of [0,800) 
#and refers to the index of the document in the term-document frequency matrix for train documents. 
#The classId refers to one of the two classes and takes one of the values 0 (for Windows) or 1 (for Hockey).


#trainClasses = trainClasses.drop(trainClasses.columns[0], axis=1)
trainClasses.head()

1
0   
0  0
1  1
2  0
3  1
4  0

In [44]:
#trainMatrixModified.txt: the term-document frequency matrix for the training documents. 
#Each row of this matrix corresponds to one the terms and each column corresponds to one the documents 
#and the (i,j)th element of the matrix shows the frequency of the ith term in the jth document. 
#This matrix contains 5500 rows and 800 columns.

trainMatrixModified.head()#, trainMatrix.shape

0    1    2    3    4    5    6    7    8    9    ...  790  791  792  793  \
0  2.0  0.0  0.0  2.0  2.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  3.0  0.0   
2  2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  1.0  1.0  1.0  1.0  1.0  1.0  2.0  1.0  1.0  1.0  ...  1.0  1.0  1.0  1.0   
4  8.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  2.0  0.0   

   794  795  796  797  798  799  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  1.0  1.0  1.0  1.0  1.0  1.0  
4  0.0  0.0  0.0  0.0  0.0  1.0  

[5 rows x 800 columns]

In [9]:
trainMatrixt.shape

(800, 5500)

__a. Create your own KNN classifier function. Your classifier should allow as input the training data matrix, the training labels, the instance to be classified, the value of K, and should return the predicted class for the instance and the top K neighbors. Your classifier should work with Euclidean distance as well as Cosine Similarity. You may create two separate classifiers, or add this capability as a parameter for the classifier function.__


In [10]:
#input: (training data matrix, training labels, the instance to be classified, the value of k, 
#and measure either euclidean or cosine similarity)

#output: predicted class for the instance and the top k neihhbors

def knn_search(train_data, train_label, instance, k, measure):
    if measure == 0:
        distance = np.sqrt(((train_data - instance)**2).sum(axis=1))
            
    elif measure == 1:
             # first find the vector norm for each instance in D as wel as the norm for vector x
        Data_norm = np.array([np.linalg.norm(train_data[i]) for i in range(len(train_data))])
        Instance_norm = np.linalg.norm(instance)
           # Compute Cosine: divide the dot product o x and each instance in D by the product of the two norms
        Similarity = np.dot(train_data,instance)/(Data_norm * Instance_norm)
           # The distance measure will be the inverse of Cosine similarity
        distance = 1 - Similarity
    indexes = np.argsort(distance)
    # predicted class for the instance and the top K neighbors
    return train_label.iloc[indexes[:k]][1].value_counts().idxmax(), indexes[:k] 

In [11]:
#using Euclidean Distance
predicted_class, k_neighbors = knn_search(trainMatrixt, trainClasses, testMatrixt[4], 5, 0)

In [12]:
print ('The Predicted Class is : ', predicted_class)
print ('The top k_neighbhors: ', k_neighbors)


The Predicted Class is :  1
The top k_neighbhors:  [204 564 798 757 743]


In [13]:
#Using Cosine Similarity
predicted_class, k_neighbors = knn_search(trainMatrixt, trainClasses, testMatrixt[6,:], 6, 1)

In [14]:
print ('The Predicted Class is : ', predicted_class)
print ('The top k_neighbhors: ', k_neighbors)

The Predicted Class is :  1
The top k_neighbhors:  [ 91 675 514 268 735 527]


__b. Create a function to compute the classification accuracy over the test data set (ratio of correct predictions to the number of test instances). This function will call the classifier function in part a on all the test instances and in each case compares the actual test class label to the predicted class label.__


In [15]:
#input: (training data matrix, training labels, the instance to be classified, the value of k, 
#measure = 0: euclidean, 1: cosine similarity

def accuracy(train_data, train_label, instance, k, measure):
    number_of_test_instance = 0
    correct = 0
    for i in range (len(instance)):
        number_of_test_instance =number_of_test_instance + 1
        predicted_class, k_neighbors = knn_search(trainMatrixt, trainClasses, testMatrixt[i,:], k, measure)
        if predicted_class == train_label[1][i]:
            correct = correct + 1
    Accurracy = correct/number_of_test_instance
    return Accurracy

In [16]:
result = accuracy(trainMatrixt, trainClasses, testMatrixt,6, 0)
print (result)

0.495


__c. Run your accuracy function on a range of values for K in order to compare accuracy values for different numbers of neighbors. Do this both using Euclidean Distance as well as Cosine similarity measure. [For example, you can try evaluating your classifiers on a range of values of K from 1 through 20 and present the results as a table or a graph].__

In [17]:
#Accuracy function running ok k=1:20
Euclidean_Distance = []
Cosine_Similarity = []
for i in range(1,21):
    Euclidean_Distance.append(accuracy(trainMatrixt, trainClasses, testMatrixt,i, 0))
    Cosine_Similarity.append(accuracy(trainMatrixt, trainClasses, testMatrixt,i, 1))

In [18]:
data = {'K':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],'Euclidean_Distance':Euclidean_Distance, 'Cosine_Similarity':Cosine_Similarity} 

In [19]:
#Presenting results as a table
df = pd.DataFrame(data)
df
  

K  Euclidean_Distance  Cosine_Similarity
0    1               0.470              0.475
1    2               0.495              0.470
2    3               0.510              0.490
3    4               0.480              0.490
4    5               0.495              0.500
5    6               0.495              0.495
6    7               0.485              0.500
7    8               0.500              0.505
8    9               0.480              0.505
9   10               0.460              0.495
10  11               0.465              0.500
11  12               0.460              0.500
12  13               0.465              0.500
13  14               0.480              0.495
14  15               0.465              0.495
15  16               0.460              0.495
16  17               0.460              0.495
17  18               0.475              0.495
18  19               0.490              0.495
19  20               0.495              0.495

*it looks like it gives better value at k = 8*

__d.Using Python, modify the training and test data sets so that term weights are converted to TFxIDF weights (instead of raw term frequencies). [See class notes on text categorization]. Then, rerun your evaluation on the range of K values (as above) and compare the results to the results without using TFxIDF weights.__

In [20]:
terms = modifiedterms
len(terms   )

5500

In [21]:
TD = trainMatrix
TD.shape

(5500, 800)

In [22]:
TestD = testMatrix
TestD.shape

(5500, 200)

In [23]:
#Train Matrix
numTerms=TD.shape[0]
NDocs = TD.shape[1]

#Test Matrix
numTerms_test=TestD.shape[0]
NDocs_test = TestD.shape[1]

In [24]:
print ('Number of terms in Train Matrix:' ,numTerms)
print ('Number of documents in Train Matrix:' ,NDocs)
print ('Number of terms in Test Matrix:' ,numTerms_test)
print ('Number of documents in Test Matrix:' ,NDocs_test)


Number of terms in Train Matrix: 5500
Number of documents in Train Matrix: 800
Number of terms in Test Matrix: 5500
Number of documents in Test Matrix: 200


In [25]:
termFreqs = TD.sum(axis=1)
print(termFreqs)
termFreqsTest = TestD.sum(axis=1)
print(termFreqsTest)

[102.  11.  22. ...   2.   2.   2.]
[24.  0.  1. ...  1.  1.  1.]


In [26]:
DF = np.array([(TD!=0).sum(1)]).T
DFT = np.array([(TestD!=0).sum(1)]).T
print (DF)
print(DFT)

[[50]
 [ 7]
 [10]
 ...
 [ 2]
 [ 2]
 [ 2]]
[[15]
 [ 0]
 [ 1]
 ...
 [ 1]
 [ 1]
 [ 1]]


In [27]:
# Create a matrix with all train entries = NDocs
# Create a matrix with all test entries = NDocs_test
np.set_printoptions(precision=2,suppress=True,linewidth=120)

NMatrix=np.ones(np.shape(TD), dtype=float)*NDocs
NMatrixTest=np.ones(np.shape(TestD), dtype=float)*NDocs_test


In [28]:
# Convert each entry into IDF values
# IDF is the log of the inverse of document frequency
# Note that IDF is only a function of the term, so all columns will be identical.

IDF = np.log2(np.divide(NMatrix, DF))
IDFT = np.log2(np.divide(NMatrixTest, DFT))


C:\Users\rhame\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


In [29]:
print (IDF)
print (IDFT)

[[4.   4.   4.   ... 4.   4.   4.  ]
 [6.84 6.84 6.84 ... 6.84 6.84 6.84]
 [6.32 6.32 6.32 ... 6.32 6.32 6.32]
 ...
 [8.64 8.64 8.64 ... 8.64 8.64 8.64]
 [8.64 8.64 8.64 ... 8.64 8.64 8.64]
 [8.64 8.64 8.64 ... 8.64 8.64 8.64]]
[[3.74 3.74 3.74 ... 3.74 3.74 3.74]
 [ inf  inf  inf ...  inf  inf  inf]
 [7.64 7.64 7.64 ... 7.64 7.64 7.64]
 ...
 [7.64 7.64 7.64 ... 7.64 7.64 7.64]
 [7.64 7.64 7.64 ... 7.64 7.64 7.64]
 [7.64 7.64 7.64 ... 7.64 7.64 7.64]]


In [30]:
# Finally compute the TFxIDF values for each document-term entry
TD_tfidf = np.transpose(TD * IDF)
TD_tfidf_test = np.transpose(TestD * IDFT)


C:\Users\rhame\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in multiply
  This is separate from the ipykernel package so we can avoid doing imports until


In [31]:
pd.set_option("display.precision", 2)
TD_tfidf

array([[ 8.  , 13.67, 12.64, ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       ...,
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ]])

In [32]:
TD_tfidf_test

array([[0.  ,  nan, 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  ,  nan, 0.  , ..., 0.  , 0.  , 0.  ],
       [3.74,  nan, 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  ,  nan, 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  ,  nan, 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  ,  nan, 0.  , ..., 0.  , 0.  , 0.  ]])

In [33]:
#Accuracy function running ok K=1:20
Euclidean_Distance_Tfdif = []
Cosine_Similarity_Tfdif = []
for i in range(1,21):
    Euclidean_Distance_Tfdif.append(accuracy(TD_tfidf, trainClasses, TD_tfidf_test,i, 0))
    Cosine_Similarity_Tfdif.append(accuracy(TD_tfidf, trainClasses, TD_tfidf_test,i, 1))

In [34]:
#Presenting results as a table
data = {'K':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], 'Euclidean_Distance_Tfdif': Euclidean_Distance_Tfdif , 'Euclidean_Distance':Euclidean_Distance, 'Cosine_Similarity_Tfdif': Cosine_Similarity_Tfdif, 'Cosine_Similarity':Cosine_Similarity} 
df = pd.DataFrame(data)
df

K  Euclidean_Distance_Tfdif  Euclidean_Distance  Cosine_Similarity_Tfdif  \
0    1                      0.47                0.47                     0.47   
1    2                      0.49                0.49                     0.47   
2    3                      0.51                0.51                     0.49   
3    4                      0.48                0.48                     0.49   
4    5                      0.49                0.49                     0.50   
5    6                      0.49                0.49                     0.49   
6    7                      0.48                0.48                     0.50   
7    8                      0.50                0.50                     0.51   
8    9                      0.48                0.48                     0.51   
9   10                      0.46                0.46                     0.49   
10  11                      0.47                0.47                     0.50   
11  12                      0.46                0.46                     0.50   
12  13                      0.47                0.47                     0.50   
13  14                      0.48                0.48                     0.49   
14  15                      0.47                0.47                     0.49   
15  16                      0.46                0.46                     0.49   
16  17                      0.46                0.46                     0.49   
17  18                      0.47                0.47                     0.49   
18  19                      0.49                0.49                     0.49   
19  20                      0.49                0.49                     0.49   

    Cosine_Similarity  
0                0.47  
1                0.47  
2                0.49  
3                0.49  
4                0.50  
5                0.49  
6                0.50  
7                0.51  
8                0.51  
9                0.49  
10               0.50  
11               0.50  
12               0.50  
13               0.49  
14               0.49  
15               0.49  
16               0.49  
17               0.49  
18               0.49  
19               0.49

*results look the same and k=8 gives better accuracy values*

__e. Create a new classifier based on the Rocchio Method adapted for text categorization [See class notes on text categorization]. You should separate the training function from the classification function. The training part for the classifier can be implemented as a function that takes as input the training data matrix and the training labels, returning the prototype vectors for each class. The classification part can be implemented as another function that would take as input the prototypes returned from the training function and the instance to be classified. This function should measure Cosine similarity of the test instance to each prototype vector. Your output should indicate the predicted class for the test instance and the similarity values of the instance to each of the category prototypes. Finally, compute the classification accuracy using the test instances and compare your results to the best KNN approach you tried earlier.__

In [547]:
print(TD_tfidf.shape)
print(labels.shape)



(800, 5500)
(800, 1)


800

In [636]:
def trainingFunc(train_data, train_label):
     #(init. prototype vectors)
    class_0 = []
    class_1 = []
   
    for i in range (len(train_label)):
        if train_label[i]==0:
            class_0.append(int(train_label[i]))
        else:
            class_1.append(int(train_label[i]))
    P0=(np.array(pd.DataFrame(class_0)))
    P1=(np.array(pd.DataFrame(class_1)))
    return P0,P1
    

In [637]:
P0,P1 = trainingFunc(TD_tfidf, labels)

In [625]:
def Rocchio_Classify(P0,P1,instance):
    Class0Norm = np.linalg.norm(P0)
    Class1Norm = np.linalg.norm(P1)
    Instance_norm = np.linalg.norm(instance)
    Similarity1 = np.dot(P0,instance)/(Class0Norm * Instance_norm)
    Similarity2= np.dot(P1,instance)/(Class1Norm * Instance_norm)
    if Similarity1 >= Similarity2:
        return 1, Similarity1, Similarity2
    else:
        return 0, Similarity1, Similarity2

In [ ]:
Rocchio_Classify(P0,P1,testMatrixt[4])