# Rasheed Hameed
# Assignment 3 - PCA for Reduced Dimensionality in Clustering


__For this problem you will use an image segmentation data set for clustering. You will experiment with using PCA as an approach to reduce dimensionality and noise in the data. You will compare the results of clustering the data with and without PCA using the provided image class assignments as the ground truth. The data set is divided into three files. The file "segmentation_data.txt" contains data about images with each line corresponding to one image. Each image is represented by 19 features (these are the columns in the data and correspond to the feature names in the file "segmentation_names.txt". The file "segmentation_classes.txt" contains the class labels (the type of image) and a numeric class label for each of the corresponding images in the data file. After clustering the image data, you will use the class labels to measure completeness and homogeneity of the generated clusters. The data set used in this problem is based on the Image Segmentation data set at the UCI Machine Learning Repository.__

In [1]:
#Loading libraries

import pandas as pd
import numpy as np
import pylab as pl
import matplotlib.pyplot as plt
#to suppresss the orange warnings
import warnings
warnings.filterwarnings("ignore")


__a. Load in the image data matrix (with rows as images and columns as features). Also load in the numeric class labels from the segmentation class file. Using your favorite method (e.g., sklearn's min-max scaler), perform min-max normalization on the data matrix so that each feature is scaled to [0,1] range.__

In [2]:
#Read the data into panda's dataframe
segmentation_data = pd.read_csv("segmentation_data/segmentation_data.txt", header=None)
segmentation_data.head(5)

0      1   2    3    4         5         6         7         8   \
0  110.0  189.0   9  0.0  0.0  1.000000  0.666667  1.222222  1.186342   
1   86.0  187.0   9  0.0  0.0  1.111111  0.720082  1.444444  0.750309   
2  225.0  244.0   9  0.0  0.0  3.388889  2.195113  3.000000  1.520234   
3   47.0  232.0   9  0.0  0.0  1.277778  1.254621  1.000000  0.894427   
4   97.0  186.0   9  0.0  0.0  1.166667  0.691215  1.166667  1.005540   

          9          10         11         12        13         14         15  \
0  12.925926  10.888889   9.222222  18.666668 -6.111111 -11.111111  17.222221   
1  13.740741  11.666667  10.333334  19.222221 -6.222222 -10.222222  16.444445   
2  12.259259  10.333334   9.333334  17.111110 -5.777778  -8.777778  14.555555   
3  12.703704  11.000000   9.000000  18.111110 -5.111111 -11.111111  16.222221   
4  15.592592  13.888889  11.777778  21.111110 -5.111111 -11.444445  16.555555   

          16        17        18  
0  18.666668  0.508139  1.910864  
1  19.222221  0.463329  1.941465  
2  17.111110  0.480149  1.987902  
3  18.111110  0.500966  1.875362  
4  21.111110  0.442661  1.863654

In [3]:
segmentation_names = pd.read_csv("segmentation_data/segmentation_names.txt", header=None)
segmentation_names.head(5)

0
0   REGION-CENTROID-COL
1   REGION-CENTROID-ROW
2    REGION-PIXEL-COUNT
3  SHORT-LINE-DENSITY-5
4  SHORT-LINE-DENSITY-2

In [4]:
segmentation_classes = pd.read_csv("segmentation_data/segmentation_classes.txt", header=None, sep='\t')
segmentation_classes.head()

0  1
0  GRASS  0
1  GRASS  0
2  GRASS  0
3  GRASS  0
4  GRASS  0

In [5]:
segmentation_data.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], dtype='int64')

In [6]:
from sklearn import preprocessing


In [7]:
min_max_scaler = preprocessing.MinMaxScaler().fit(segmentation_data)
min_max_norm = min_max_scaler.transform(segmentation_data)
min_max_norm.shape

(2100, 19)

__b. Next, Perform Kmeans clustering (for this problem, use the Kmeans implementation in scikit-learn) on the image data (since there are a total 7 pre-assigned image classes, you should use K = 7 in your clustering). Use Euclidean distance as your distance measure for the clustering. Print the cluster centroids (use some formatting so that they are visually understandable). Compare your 7 clusters to the 7 pre-assigned classes by computing the Completeness and Homogeneity values of the generated clusters.__

In [8]:
from sklearn.cluster import KMeans 

In [9]:
kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1) # initialization

In [10]:
kmeans.fit(min_max_norm)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 390.8801195140035
start iteration
done sorting
end inner loop
Iteration 1, inertia 370.1693897801342
start iteration
done sorting
end inner loop
Iteration 2, inertia 363.4060873226682
start iteration
done sorting
end inner loop
Iteration 3, inertia 358.4869806053015
start iteration
done sorting
end inner loop
Iteration 4, inertia 356.29017349867274
start iteration
done sorting
end inner loop
Iteration 5, inertia 354.53793744416174
start iteration
done sorting
end inner loop
Iteration 6, inertia 353.67654311173675
start iteration
done sorting
end inner loop
Iteration 7, inertia 352.7754920865792
start iteration
done sorting
end inner loop
Iteration 8, inertia 351.64959054845565
start iteration
done sorting
end inner loop
Iteration 9, inertia 351.3688322800115
start iteration
done sorting
end inner loop
Iteration 10, inertia 351.31304417937207
start iteration
done sorting
end inner loop
Iteration 11,

Iteration 0, inertia 401.89334039631257
start iteration
done sorting
end inner loop
Iteration 1, inertia 375.6267485618109
start iteration
done sorting
end inner loop
Iteration 2, inertia 369.44807584977843
start iteration
done sorting
end inner loop
Iteration 3, inertia 368.1617289956305
start iteration
done sorting
end inner loop
Iteration 4, inertia 367.8944518256418
start iteration
done sorting
end inner loop
Iteration 5, inertia 367.7489370036908
start iteration
done sorting
end inner loop
Iteration 6, inertia 367.66918257054306
start iteration
done sorting
end inner loop
Iteration 7, inertia 367.63237451955797
start iteration
done sorting
end inner loop
Iteration 8, inertia 367.6278241081004
start iteration
done sorting
end inner loop
Iteration 9, inertia 367.62704175365
center shift 1.646776e-03 within tolerance 4.150157e-06
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 384.8181877789614
start iteration
done sorting
end inner loop
Itera

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
       n_clusters=7, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=1)

In [11]:
clusters = kmeans.predict(min_max_norm)

In [12]:
print (clusters)

[5 5 5 ... 4 4 2]


In [13]:
print (kmeans.cluster_centers_)

[[2.54169148e-01 4.59974315e-01 0.00000000e+00 2.62557070e-02
  1.36986301e-02 3.72740781e-02 2.36373158e-03 2.78737326e-02
  2.01697950e-03 2.60125428e-02 1.79253350e-02 4.23063731e-02
  1.65040194e-02 7.69800402e-01 2.16011286e-01 5.08116519e-01
  4.32949340e-02 8.01686648e-01 1.81153270e-01]
 [3.02505527e-01 5.30861582e-01 0.00000000e+00 5.22598854e-02
  4.66101695e-02 1.00816850e-01 9.42021613e-03 8.39719910e-02
  1.10432753e-02 4.00608091e-01 3.70347226e-01 4.72460748e-01
  3.53035779e-01 4.97146165e-01 5.70882355e-01 2.13054402e-01
  4.72460748e-01 3.02263027e-01 1.63879166e-01]
 [2.56103232e-01 3.93468137e-01 0.00000000e+00 7.45098018e-02
  1.91176471e-02 7.73428799e-02 4.10042113e-03 6.05736165e-02
  4.96748748e-03 1.48187304e-01 1.38085139e-01 1.85159837e-01
  1.18538808e-01 7.16906282e-01 3.44013845e-01 3.55458216e-01
  1.85413237e-01 4.11986237e-01 2.01889852e-01]
 [5.35098814e-01 1.50166667e-01 0.00000000e+00 2.77777769e-02
  1.66666667e-03 3.02281387e-02 5.42887957e-04 2.6

In [14]:
#Cluster 0-6 represented with names
pd.DataFrame(kmeans.cluster_centers_.T, index=segmentation_names)

0         1         2         3         4  \
(REGION-CENTROID-COL,)   0.254169  0.302506  0.256103  0.535099  0.770674   
(REGION-CENTROID-ROW,)   0.459974  0.530862  0.393468  0.150167  0.425215   
(REGION-PIXEL-COUNT,)    0.000000  0.000000  0.000000  0.000000  0.000000   
(SHORT-LINE-DENSITY-5,)  0.026256  0.052260  0.074510  0.027778  0.013978   
(SHORT-LINE-DENSITY-2,)  0.013699  0.046610  0.019118  0.001667  0.022581   
(VEDGE-MEAN,)            0.037274  0.100817  0.077343  0.030228  0.040237   
(VEDGE-SD,)              0.002364  0.009420  0.004100  0.000543  0.002989   
(HEDGE-MEAN,)            0.027874  0.083972  0.060574  0.026766  0.023122   
(HEDGE-SD,)              0.002017  0.011043  0.004967  0.000587  0.002088   
(INTENSITY-MEAN,)        0.026013  0.400608  0.148187  0.823246  0.041138   
(RAWRED-MEAN,)           0.017925  0.370347  0.138085  0.779716  0.035005   
(RAWBLUE-MEAN,)          0.042306  0.472461  0.185160  0.894170  0.058340   
(RAWGREEN-MEAN,)         0.016504  0.353036  0.118539  0.788761  0.028766   
(EXRED-MEAN,)            0.769800  0.497146  0.716906  0.270665  0.778473   
(EXBLUE-MEAN,)           0.216011  0.570882  0.344014  0.666373  0.223939   
(EXGREEN-MEAN,)          0.508117  0.213054  0.355458  0.289386  0.486509   
(VALUE-MEAN,)            0.043295  0.472461  0.185413  0.894170  0.059295   
(SATURATION-MEAN,)       0.801687  0.302263  0.411986  0.211804  0.538181   
(HUE-MEAN,)              0.181153  0.163879  0.201890  0.125066  0.243969   

                                5         6  
(REGION-CENTROID-COL,)   0.513994  0.750696  
(REGION-CENTROID-ROW,)   0.808937  0.534564  
(REGION-PIXEL-COUNT,)    0.000000  0.000000  
(SHORT-LINE-DENSITY-5,)  0.077441  0.040000  
(SHORT-LINE-DENSITY-2,)  0.005051  0.038462  
(VEDGE-MEAN,)            0.054474  0.114419  
(VEDGE-SD,)              0.001407  0.019301  
(HEDGE-MEAN,)            0.046335  0.109240  
(HEDGE-SD,)              0.001401  0.017999  
(INTENSITY-MEAN,)        0.108790  0.300955  
(RAWRED-MEAN,)           0.091403  0.279908  
(RAWBLUE-MEAN,)          0.092414  0.352738  
(RAWGREEN-MEAN,)         0.142676  0.265920  
(EXRED-MEAN,)            0.679161  0.592572  
(EXBLUE-MEAN,)           0.079002  0.451124  
(EXGREEN-MEAN,)          0.821287  0.309158  
(VALUE-MEAN,)            0.134901  0.352822  
(SATURATION-MEAN,)       0.414491  0.302342  
(HUE-MEAN,)              0.892333  0.164764

In [15]:
from sklearn.metrics import completeness_score, homogeneity_score

In [16]:
print (completeness_score(segmentation_classes[1],clusters))

0.6131870124853013


In [17]:
print (homogeneity_score(segmentation_classes[1],clusters))

0.6115021163370863


__c. Perform PCA on the normalized image data matrix. You may use the linear algebra package in Numpy or the Decomposition module in scikit-learn (the latter is much more efficient). Analyze the principal components to determine the number, r, of PCs needed to capture at least 95% of variance in the data. Then use these r components as features to transform the data into a reduced dimension space.__

In [18]:
from sklearn import decomposition

In [34]:
pca = decomposition.PCA(n_components=5)
SegTrans = pca.fit(min_max_norm).transform(min_max_norm)

In [35]:
np.set_printoptions(precision=2,suppress=True)
print (SegTrans)

[[-0.69  0.53  0.25 -0.2  -0.08]
 [-0.67  0.51  0.34 -0.17 -0.04]
 [-0.71  0.77 -0.16 -0.01 -0.17]
 ...
 [-0.51 -0.13 -0.08  0.1  -0.03]
 [-0.48 -0.09 -0.16  0.11  0.  ]
 [-0.44 -0.11 -0.05  0.15  0.02]]


In [36]:
print(pca.explained_variance_ratio_)

[0.61 0.13 0.1  0.05 0.04]


*above makes it 98% and we will reduce 1 component to get to 95%*

In [45]:
pca = decomposition.PCA(n_components=6)
SegTrans = pca.fit(min_max_norm).transform(min_max_norm)

In [46]:
print(pca.explained_variance_ratio_.sum()*100)

94.11392197960623


In [47]:
SegTrans.shape

(2100, 6)

*We went from 19 to 4 attributes space*

__d. Perform Kmeans again, but this time on the lower dimensional transformed data. Then, compute the Completeness and Homogeneity values of the new clusters.__

In [48]:
kmeans.fit(SegTrans)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 306.41623347636005
start iteration
done sorting
end inner loop
Iteration 1, inertia 289.0475997613696
start iteration
done sorting
end inner loop
Iteration 2, inertia 281.76662366638953
start iteration
done sorting
end inner loop
Iteration 3, inertia 275.30287920589683
start iteration
done sorting
end inner loop
Iteration 4, inertia 268.9378284224315
start iteration
done sorting
end inner loop
Iteration 5, inertia 261.8599372472873
start iteration
done sorting
end inner loop
Iteration 6, inertia 258.46033582251
start iteration
done sorting
end inner loop
Iteration 7, inertia 257.3121232374316
start iteration
done sorting
end inner loop
Iteration 8, inertia 256.9363392091849
start iteration
done sorting
end inner loop
Iteration 9, inertia 256.8383315700721
start iteration
done sorting
end inner loop
Iteration 10, inertia 256.83527793039457
center shift 2.615258e-03 within tolerance 1.236861e-05
Init

end inner loop
Iteration 10, inertia 276.7857787180433
start iteration
done sorting
end inner loop
Iteration 11, inertia 276.51293083110596
start iteration
done sorting
end inner loop
Iteration 12, inertia 276.38276347735086
start iteration
done sorting
end inner loop
Iteration 13, inertia 276.2706064301683
start iteration
done sorting
end inner loop
Iteration 14, inertia 276.1228620107969
start iteration
done sorting
end inner loop
Iteration 15, inertia 275.79484927116107
start iteration
done sorting
end inner loop
Iteration 16, inertia 275.6214193189086
start iteration
done sorting
end inner loop
Iteration 17, inertia 275.380840058606
start iteration
done sorting
end inner loop
Iteration 18, inertia 274.94756155752714
start iteration
done sorting
end inner loop
Iteration 19, inertia 274.40366052328693
start iteration
done sorting
end inner loop
Iteration 20, inertia 273.4331330754759
start iteration
done sorting
end inner loop
Iteration 21, inertia 271.02827439886516
start iteration


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
       n_clusters=7, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=1)

In [49]:
clusters = kmeans.predict(SegTrans)

In [50]:
print (kmeans.cluster_centers_)

[[-0.6  -0.36  0.11 -0.13 -0.13 -0.02]
 [ 1.41  0.09  0.04 -0.17 -0.03 -0.01]
 [-0.62  0.64  0.2  -0.09 -0.06  0.01]
 [-0.2  -0.24  0.15  0.06  0.13 -0.01]
 [ 0.18  0.05 -0.27  0.19  0.03  0.02]
 [-0.51 -0.07 -0.34 -0.07  0.07  0.01]
 [ 0.44 -0.1   0.17  0.24 -0.05 -0.01]]


In [51]:
print (completeness_score(segmentation_classes[1],clusters))

0.6092856703592695


In [52]:
print (homogeneity_score(segmentation_classes[1],clusters))

0.60763353032105


__e. Discuss your observations based on the comparison of the two clustering result__

*We were able to reduce the dimensional space down to 6 components and 95% variance and improve both completness and homegeneity improved with less attributes.*